spring:
  datasource:
    url: jdbc:mysql://39.107.85.38:3306/inventory2?userSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: 80B2EBCE9A51C318@MonolithIoT